### ISSUE TITLE
Line 4 in Table I

### ISSUE THREAD

**Issue by smiths** [smiths/spreadOverTimeAndTeam#23]
Line 4 of the data in Table I seems to be spaced oddly.  The line below covers part of the text.

**Comment by CSchank** [comment]
Hmm, I don't see the issue, can you send a screenshot of what you are seeing?

<img width="443" alt="image" src="https://github.com/user-attachments/assets/fa007ad6-2b41-42b9-a574-e9084279df4e">

**Comment by smiths** [comment]
The problem has gone away.  As soon as I took a screenshot, the problem disappeared.  :smile:  I think it was an artifact of the specific size I was viewing the paper.  When I made it smaller, it disappeared, and now I can't get it to reappear.

I saw it multiple times, but I can't reproduce it, so let's close this issue.  :smile:
