### ISSUE TITLE
Write details of new fairness metric

### ISSUE THREAD

**Issue by CSchank** [smiths/spreadOverTimeAndTeam#6]

**Comment by smiths** [comment]
We don't have much space in the paper, so you won't have to write much.  :smile:  If you could motivate the definition with your practical arguments, that would be great.  I particularly like that the metric is based on the disparity of commit count between all combinations of team members.

**Comment by CSchank** [comment]
Wrote this in #8. With two graphs, it's just over half a page. Let me know if that's too long. I figured I'd put in both graphs for now and we can remove or trim the text if needed later.

**Comment by smiths** [comment]
Looks great.  I agree that we can include everything you've written for now.  We still have some space to play with.  We are allowed 5 pages, with an extra page for citations.

**Comment by CSchank** [comment]
Great. I will close this issue for now since we have it written, as well as #7.

**Comment by CSchank** [comment]
Oops, I should reopen because I just realized: in the abstract it says we'll compare to Jain's - do you want me to still? If so, I'll find a citation. Probably a good idea to at least mention it, since someone will likely bring it up. I originally meant to when I talk about the 0-1 and meaningful-between-value benefits.

**Comment by smiths** [comment]
We should change the abstract to not mention Jain's index.  I agree that there is no value, especially in the limited space, to present both metrics.  You are right though that in the body of the text you should reference Jain's index as another alternative.  Providing a citation to Jain is a good idea.

**Comment by CSchank** [comment]
Sounds good, yes, my plan was to just reference Jain but say that we developed our own to meet the criteria I already listed.

**Comment by smiths** [comment]
I updated the abstract in 56dfa47.

**Comment by CSchank** [comment]
I tried something else I thought of, which was running each team's daily commits through the fairness metric. Of course, the closer to 1 they are, the more they evenly spread their work out. 0 would mean they did all their commits on one day. 

There is an overall negative Pearson's correlation metric between these two for 2022/23, and a slight positive correlation in 2023/24. The former could tell us that teams that have more unfair work means that there is one person who "takes over" and does a lot of the work, and is really interested so they commit much more often, spreading out over time but not team. It also might mean that teams who spread out the work amongst themselves do so in more discrete "sprints" perhaps together in a "hackathon" style. The latter year indicates a bit of improvement, which is good to see.

At first I didn't know if I wanted to include it, but a "correlation between time-spread and team-spread" section sounds really cool actually. Do you think we have space?

<img width="610" alt="image" src="https://github.com/user-attachments/assets/147c4a51-7c2f-4e51-96e8-f36316b1f0b4">

<img width="624" alt="image" src="https://github.com/user-attachments/assets/46eca17a-1809-4df3-bdef-87878aae7db5">

**Comment by smiths** [comment]
Very neat!  Time is a resource that they should use fairly.  Do they spread their work out over time, in the extreme using each day an equal amount, or do some days get more activity.  If we have space we should try to include this.  We won't have room for both plots, and we'll probably have to remove at least one plot that is already in the paper.

**Comment by smiths** [comment]
The fairness metric section has been written.
