### ISSUE TITLE
Data Availability Section

### ISSUE THREAD

**Issue by CSchank** [smiths/spreadOverTimeAndTeam#9]
According to the CSEE&T website:

"CSEE&T 2025 aims to follow the ICSE 2025 Open Science policies. In summary, the steering principle is that research results should be made accessible to the public and empirical studies should be reproducible whenever possible. In particular, we actively support the adoption of open data and open source principles and encourage all contributing authors to disclose (anonymized and curated) data to increase reproducibility and replicability whenever allowable and applicable.

We are aware that some datasets and tools may not be made open and public (e.g., when prohibited by a Non-Disclosure Agreement, when the Ethics Review Board forbids sharing data for participant privacy, when tool source code is commercial-in-confidence, etc.). We also recognize that reproducibility or replicability is not a goal in qualitative research and that, similar to industrial studies, qualitative studies often face challenges in sharing research data. For guidelines on how to report qualitative research to ensure the assessment of the reliability and credibility of research results, see the ICSE 2025 Open Science page. Note that sharing research data is not mandatory for submission or acceptance. However, non-sharing needs to be justified.

**IMPORTANT: We therefore ask all authors to provide a supporting statement on the data availability (or lack thereof) in their submitted papers in a section named Data Availability after the Conclusion section. Authors can also provide anonymized links to anonymized data and repositories in that section or can upload anonymized data using the supplementary material upload option during submission process via the [HotCRP submission site](https://cseet25.hotcrp.com/). Authors who cannot disclose data should provide a short statement explaining the reasons why they cannot share the data in the Data Availability section of their paper, after the Conclusion section.**

Authors are asked to carefully review any supplementary material to ensure it conforms to the double-anonymous policy employed for ICSE 2025. For example, code and data repositories may be exported to remove version control history, scrubbed of names in comments and metadata, and anonymously uploaded to a sharing site to support review. Below are some resources that can be helpful:"

@smiths We need to address this. What do you think about saying "Data is available upon request" essentially?

**Comment by smiths** [comment]
Thank you @CSchank for noticing this.  I wouldn't have noticed until I was submitting the paper some time on Thursday.  :smile:

Could we just put the data you have in our repo on GitHub?  We would redact the link in the submitted paper, but then reveal the link should the paper be accepted?  Nobody will look at the data, but then we can say it is available.  I like this better than available upon request.  We don't need to make the data look nice.  Just the raw numbers in a csv file would be fine.

**Comment by smiths** [comment]
We resolved this conversation so the issue can be closed.
